// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz762vk1bpuxDUGe3k6s3UlhJNZXfalGs',
    appId: '1:81534062142:web:d1a31b564bb269978c4b6f',
    messagingSenderId: '81534062142',
    projectId: 'uzonlinesavdo',
    authDomain: 'uzonlinesavdo.firebaseapp.com',
    storageBucket: 'uzonlinesavdo.firebasestorage.app',
    measurementId: 'G-Q8X1Z6X557',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNtRCa-au2QlkUTiV_sBfk3v65Wxm3w-M',
    appId: '1:81534062142:android:37a4ca234903d5e58c4b6f',
    messagingSenderId: '81534062142',
    projectId: 'uzonlinesavdo',
    storageBucket: 'uzonlinesavdo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPG77F-tzfTbUDajoltFMm5n5wcQy7_CM',
    appId: '1:81534062142:ios:9a9b98fafdbad1bc8c4b6f',
    messagingSenderId: '81534062142',
    projectId: 'uzonlinesavdo',
    storageBucket: 'uzonlinesavdo.firebasestorage.app',
    iosBundleId: 'com.example.onlineSavdo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPG77F-tzfTbUDajoltFMm5n5wcQy7_CM',
    appId: '1:81534062142:ios:9a9b98fafdbad1bc8c4b6f',
    messagingSenderId: '81534062142',
    projectId: 'uzonlinesavdo',
    storageBucket: 'uzonlinesavdo.firebasestorage.app',
    iosBundleId: 'com.example.onlineSavdo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz762vk1bpuxDUGe3k6s3UlhJNZXfalGs',
    appId: '1:81534062142:web:2e18a2242a704f728c4b6f',
    messagingSenderId: '81534062142',
    projectId: 'uzonlinesavdo',
    authDomain: 'uzonlinesavdo.firebaseapp.com',
    storageBucket: 'uzonlinesavdo.firebasestorage.app',
    measurementId: 'G-T2SKGQNPE5',
  );
}
